"""CLI commands for C2I (Cosmology to Intermediates) operations.

This module provides commands for computing intermediate data products
from cosmological parameters.
"""

from pathlib import Path

import click

from c2i2o.c2i_calculator import C2ICalculator
from c2i2o.cli.main import cli
from c2i2o.cli.option import (
    config_file_arg,
    input_file_opt,
    output_file_opt,
    overwrite_opt,
    verbose_opt,
)


@cli.group()
def c2i() -> None:
    """Commands for cosmology to intermediates (C2I) operations.

    This group provides tools for computing intermediate data products
    from cosmological parameters.
    """


@c2i.command()
@config_file_arg()
@input_file_opt
@output_file_opt()
@overwrite_opt()
@verbose_opt()
def compute(
    config_file: Path,
    input_file: Path,
    output: Path,
    overwrite: bool,
    verbose: bool,
) -> None:
    """Compute intermediate data products from cosmological parameters.

    Reads a C2ICalculator configuration from CONFIG_FILE (YAML) and applies it
    to cosmological parameters from the input HDF5 file, generating intermediate
    data products and saving them to an output HDF5 file.

    Example:

        c2i2o c2i compute calculator.yaml -i params.h5 -o intermediates.h5 -v

    The configuration file should define a complete C2ICalculator including:
    - Baseline cosmology
    - Computation definitions (grids, functions)

    The input file should contain cosmological parameters as generated by:

        c2i2o cosmo generate config.yaml -o params.h5 -s 42

    The output file will contain intermediate data products with structure:

        sample_000_chi: (n_grid_points,) float64
        sample_000_P_lin: (n_a_points, n_k_points) float64
        sample_001_chi: (n_grid_points,) float64
        ...
    """
    if verbose:
        click.echo(f"Loading calculator configuration from: {config_file}")

    # Check if output file exists and handle overwrite
    if output.exists() and not overwrite:
        raise click.ClickException(f"Output file {output} already exists. Use --overwrite to replace it.")

    try:
        # Load calculator from YAML
        calculator = C2ICalculator.from_yaml(config_file)

        if verbose:
            click.echo("Loaded calculator configuration")
            n_comps = len(calculator.intermediate_calculator.computations)
            click.echo(f"  Number of computations: {n_comps}")
            comp_names = list(calculator.intermediate_calculator.computations.keys())
            click.echo(f"  Computations: {', '.join(comp_names)}")
            cosmo_type = calculator.intermediate_calculator.baseline_cosmology.cosmology_type
            click.echo(f"  Cosmology type: {cosmo_type}")

        if verbose:
            click.echo(f"Reading parameters from: {input_file}")

        # Compute intermediates from file
        calculator.compute_from_file(
            input_file=input_file,
            output_file=output,
        )

        if verbose:
            click.echo(f"Successfully wrote intermediates to: {output}")

        click.secho(f"Computed intermediates: {output}", fg="green")

    except FileNotFoundError as e:  # pragma: no cover
        raise click.ClickException(f"File not found: {e}") from e
    except ValueError as e:
        raise click.ClickException(f"Invalid configuration or data: {e}") from e
    except Exception as e:  # pragma: no cover
        raise click.ClickException(f"Error computing intermediates: {e}") from e
