"""CLI commands for C2I (Cosmology to Intermediates) operations.

This module provides commands for computing intermediate data products
from cosmological parameters.
"""

from pathlib import Path

import click

from c2i2o.c2i_calculator import C2ICalculator
from c2i2o.cli.main import cli
from c2i2o.cli.option import (
    config_file_arg,
    input_file_opt,
    output_file_opt,
    overwrite_opt,
    verbose_opt,
    emulator_path_opt,
    emulator_output_opt,
    epochs_opt,
    batch_size_opt,
    validation_split_opt,
    early_stopping_opt,
    patience_opt,    
)


@cli.group()
def c2i() -> None:
    """Commands for cosmology to intermediates (C2I) operations.

    This group provides tools for computing intermediate data products
    from cosmological parameters.
    """


@c2i.command()
@config_file_arg()
@input_file_opt
@output_file_opt()
@overwrite_opt()
@verbose_opt()
def compute(
    config_file: Path,
    input_file: Path,
    output: Path,
    overwrite: bool,
    verbose: bool,
) -> None:
    """Compute intermediate data products from cosmological parameters.

    Reads a C2ICalculator configuration from CONFIG_FILE (YAML) and applies it
    to cosmological parameters from the input HDF5 file, generating intermediate
    data products and saving them to an output HDF5 file.

    Example:

        c2i2o c2i compute calculator.yaml -i params.h5 -o intermediates.h5 -v

    The configuration file should define a complete C2ICalculator including:
    - Baseline cosmology
    - Computation definitions (grids, functions)

    The input file should contain cosmological parameters as generated by:

        c2i2o cosmo generate config.yaml -o params.h5 -s 42

    The output file will contain intermediate data products with structure:

        sample_000_chi: (n_grid_points,) float64
        sample_000_P_lin: (n_a_points, n_k_points) float64
        sample_001_chi: (n_grid_points,) float64
        ...
    """
    if verbose:
        click.echo(f"Loading calculator configuration from: {config_file}")

    # Check if output file exists and handle overwrite
    if output.exists() and not overwrite:
        raise click.ClickException(f"Output file {output} already exists. Use --overwrite to replace it.")

    try:
        # Load calculator from YAML
        calculator = C2ICalculator.from_yaml(config_file)

        if verbose:
            click.echo("Loaded calculator configuration")
            n_comps = len(calculator.intermediate_calculator.computations)
            click.echo(f"  Number of computations: {n_comps}")
            comp_names = list(calculator.intermediate_calculator.computations.keys())
            click.echo(f"  Computations: {', '.join(comp_names)}")
            cosmo_type = calculator.intermediate_calculator.baseline_cosmology.cosmology_type
            click.echo(f"  Cosmology type: {cosmo_type}")

        if verbose:
            click.echo(f"Reading parameters from: {input_file}")

        # Compute intermediates from file
        calculator.compute_from_file(
            input_file=input_file,
            output_file=output,
        )

        if verbose:
            click.echo(f"Successfully wrote intermediates to: {output}")

        click.secho(f"Computed intermediates: {output}", fg="green")

    except FileNotFoundError as e:  # pragma: no cover
        raise click.ClickException(f"File not found: {e}") from e
    except ValueError as e:
        raise click.ClickException(f"Invalid configuration or data: {e}") from e
    except Exception as e:  # pragma: no cover
        raise click.ClickException(f"Error computing intermediates: {e}") from e


@c2i.command("train-emulator")
@config_file_arg
@input_file_opt
@output_file_opt
@emulator_output_opt
@epochs_opt
@batch_size_opt
@validation_split_opt
@early_stopping_opt
@patience_opt
@verbose_opt
def train_emulator(
    config_file,
    input,
    output,
    emulator_output,
    epochs,
    batch_size,
    validation_split,
    early_stopping,
    patience,
    verbose,
):
    """Train a C2I emulator from data files.

    This command trains a neural network emulator to predict intermediate
    quantities from cosmological parameters. The training configuration
    (including emulator architecture) is specified in the config file.

    Examples:

        c2i2o c2i train-emulator config.yaml --input params.hdf5 \\
            --output intermediates.hdf5 --emulator-output models/my_emulator \\
            --epochs 200

        c2i2o c2i train-emulator config.yaml --input params.hdf5 \\
            --output intermediates.hdf5 --emulator-output models/my_emulator \\
            --early-stopping --patience 15 --verbose
    """
    from c2i2o.c2i_train_emulation import C2ITrainEmulator

    # Load trainer configuration
    if verbose:
        click.echo(f"Loading training configuration from {config_file}...")

    trainer = C2ITrainEmulator.from_yaml(config_file)

    # Train from files
    if verbose:
        click.echo(f"Loading training data from {input} and {output}...")
        click.echo(f"Training emulator '{trainer.emulator.name}'...")
        click.echo(f"  Intermediates: {trainer.emulator.intermediate_names}")
        click.echo(f"  Architecture: {trainer.emulator.hidden_layers}")
        click.echo(f"  Epochs: {epochs}, Batch size: {batch_size}")
        click.echo(f"  Validation split: {validation_split}")
        if early_stopping:
            click.echo(f"  Early stopping: enabled (patience={patience})")

    trainer.train_from_file(
        input_filepath=input,
        output_filepath=output,
        epochs=epochs,
        batch_size=batch_size,
        validation_split=validation_split,
        verbose=1 if verbose else 0,
        early_stopping=early_stopping,
        patience=patience,
    )

    # Save trained emulator
    if verbose:
        click.echo(f"Saving trained emulator to {emulator_output}...")

    trainer.save_emulator(emulator_output)

    click.secho(
        f"✓ Successfully trained emulator and saved to {emulator_output}",
        fg="green",
    )


@c2i.command("emulate")
@emulator_path_opt
@input_file_opt
@output_file_opt
@batch_size_opt
@overwrite_opt
@verbose_opt
def emulate(emulator_path, input, output, batch_size, overwrite, verbose):
    """Emulate intermediates using a trained emulator.

    This command loads a trained emulator and uses it to predict intermediate
    quantities for the cosmological parameters in the input file.

    Examples:

        c2i2o c2i emulate --emulator-path models/my_emulator \\
            --input test_params.hdf5 --output predictions.hdf5

        c2i2o c2i emulate --emulator-path models/my_emulator \\
            --input test_params.hdf5 --output predictions.hdf5 \\
            --batch-size 64 --verbose
    """
    from c2i2o.c2i_emulator import C2IEmulatorImpl

    # Check if output exists
    if output.exists() and not overwrite:
        click.secho(
            f"Error: Output file '{output}' already exists. Use --overwrite to replace.",
            fg="red",
            err=True,
        )
        raise click.Abort()

    # Load emulator
    if verbose:
        click.echo(f"Loading emulator from {emulator_path}...")

    emulator_impl = C2IEmulatorImpl.load_emulator(emulator_path)

    if verbose:
        info = emulator_impl.get_emulator_info()
        click.echo(f"  Emulator: {info['name']}")
        click.echo(f"  Intermediates: {info['intermediate_names']}")
        click.echo(f"  Training samples: {info['training_samples']}")
        click.echo(f"  Architecture: {info['hidden_layers']}")

    # Emulate from file
    if verbose:
        click.echo(f"Loading parameters from {input}...")
        click.echo(f"Generating predictions...")

    results = emulator_impl.emulate_from_file(
        input_filepath=input,
        output_filepath=output,
        batch_size=batch_size,
    )

    if verbose:
        click.echo(f"Generated predictions for {len(results)} parameter sets")

    click.secho(
        f"✓ Successfully emulated intermediates and saved to {output}",
        fg="green",
    )


__all__ = ["c2i"]
